Repository kubernetes-csi/docs, pull requests merged in 2018-11, with the labels that each got.

#70 Added livenessprobe configuration example for CSI driver
  book/src/Example.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#64 Updated docs for enabling topology
  book/src/Setup.md
  docs/Setup.html
  docs/book.js
  docs/css/variables.css
  docs/index.html
  docs/print.html
  docs/searchindex.js
  docs/searchindex.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#72 example: pull from upstream repos directly, use fixed revisions
  book/src/Example.md
  book/src/example/hostpath/csi-hostpath-attacher.yaml
  book/src/example/hostpath/csi-hostpath-provisioner.yaml
  book/src/example/hostpath/csi-hostpathplugin.yaml
  book/src/example/rbac/csi-attacher-rbac.yaml
  book/src/example/rbac/csi-nodeplugin-rbac.yaml
  book/src/example/rbac/csi-provisioner-rbac.yaml
  book/src/example/snapshot/csi-snapshotter-rbac.yaml
  docs/Example.html
  docs/book.js
  docs/css/variables.css
  docs/index.html
  docs/print.html
  docs/searchindex.js
  docs/searchindex.json
  hack/update-example.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#75 Update AWS EBS CSI Driver version to v0.1.0
  book/src/Drivers.md
  docs/Drivers.html
  docs/print.html
  docs/searchindex.js
  docs/searchindex.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 book/src/Drivers.md: Added CSI for MooseFS
  book/src/Drivers.md
  docs/Drivers.html
  docs/print.html
  docs/searchindex.js
  docs/searchindex.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#81 add Makefile
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#86 Add GlusterFS to snapshot supported CSI Driver list.
  book/src/Implement-Snapshot-Feature.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#74 Fix typo in example and deploying
  book/src/CSI-Kubernetes.md
  book/src/Setup.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#85 Fix CSIDriver and CSINodeInfo URLs
  book/src/Setup.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#88 Add DriveScale driver to the list
  book/src/Drivers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#83 Example: update external-snapshotter RBAC link
  book/src/Example.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#69 Update DigitalOcean CSI driver version
  book/src/Drivers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
