Repository kubernetes-csi/docs, pull requests merged in 2018-09, with the labels that each got.

#46 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#47 Add LICENSE
  LICENSE
Labels: approved, cncf-cla: yes, lgtm, size/L

#44 Added link to 'Understanding CSI' to Developing a CSI driver page
  book/src/CSI-Driver.md
  docs/CSI-Driver.html
  docs/css/variables.css
  docs/print.html
  docs/searchindex.js
  docs/searchindex.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#48 Suggestions to improve the kubelet plugin registration setup document
  book/src/Setup.md
  docs/Setup.html
  docs/print.html
  docs/searchindex.js
  docs/searchindex.json
Labels: approved, cncf-cla: yes, size/L

#51 fix typo
  book/src/Setup.md
  docs/Setup.html
  docs/print.html
  docs/searchindex.js
  docs/searchindex.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#52 Update readme to use docker image to generate doc
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#53 Add Quobyte CSI reference
  book/src/Drivers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#58 Fixed small typo in Readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
