Repository kubernetes-csi/docs, pull requests merged in 2018-10, with the labels that each got.

#55 Doc Update for Registrar Sidecar Setup with Kubelet Plugin Registration
  book/src/Setup.md
  book/src/UsingCSIDriver.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#63 Add glusterfs csi driver information to Drivers file.
  book/src/Drivers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#65 Update README
  .gitignore
  book/src/Setup.md
  book/src/example/rbac/csi-provisioner-rbac.yaml
  docs/Example.html
  docs/Setup.html
  docs/print.html
  docs/searchindex.js
  docs/searchindex.json
Labels: approved, cncf-cla: yes, lgtm, size/M
