Repository kubernetes-csi/docs, pull requests merged in 2019-07, with the labels that each got.

#182 Add info for Pure Storage CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#187 Update ceph CSI driver details in the drivers list
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#183 Deprecate cluster-driver-registrar
  book/src/SUMMARY.md
  book/src/cluster-driver-registrar.md
  book/src/csi-driver-object.md
  book/src/sidecar-containers.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#186 Fix invalid CSI compatibility version
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#170 Doc update for CSI inline ephemeral volume support
  book/src/SUMMARY.md
  book/src/ephemeral-local-volumes.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#188 Rename Pure CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
