Repository kubernetes-csi/docs, pull requests merged in 2019-06, with the labels that each got.

#167 Update Portworx driver version and name
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#166 docs: update xsky driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#163 Add ROBIN as CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#169 fix incorrect feature column for xsky driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#168 Update secrets documentation with new keys and template variables
  book/src/secrets-and-credentials.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#171 Add v1.1.1 release to external-provisioner docs
  book/src/external-provisioner.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#159 Update the Ember-CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#174 remind people to add secret RBAC rules
  book/src/secrets-and-credentials.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#176 Add MacroSAN CSI plugin to CSI driver list
  book/src/drivers.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#173 Add docs for cloning feature
  book/src/SUMMARY.md
  book/src/external-provisioner.md
  book/src/volume-cloning.md
  book/src/volume-datasources.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#178 Add volume cloning to driver support table
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#179 Fix table
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#177 Add the image driver to the driver list.
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#180 Update 1.15 versions of external sidecars and document K8s changes
  book/src/external-attacher.md
  book/src/external-provisioner.md
  book/src/external-resizer.md
  book/src/external-snapshotter.md
  book/src/kubernetes-changelog.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
