Repository kubernetes-csi/docs, pull requests merged in 2019-08, with the labels that each got.

#192 Move Kubernetes version details to a separate page that is more visible
  book/src/SUMMARY.md
  book/src/kubernetes-compatibility.md
  book/src/sidecar-containers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#190 Update Kubernetse-CSI Secret Documentation
  book/src/SUMMARY.md
  book/src/secrets-and-credentials-storage-class.md
  book/src/secrets-and-credentials-volume-snapshot-class.md
  book/src/secrets-and-credentials.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#193 Added HPE to list of CSI drivers
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#195 Add ephemeral support to HPE CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#205 Update NetApp CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
