Repository kubernetes-csi/docs, pull requests merged in 2019-12, with the labels that each got.

#232 drivers: fix hostpath and flexvolume repo links
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#233 drivers: Update StorageOS driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#234 CSI 0.3 has been removed in K8s 1.17
  book/src/external-attacher.md
  book/src/external-provisioner.md
  book/src/external-snapshotter.md
  book/src/kubernetes-changelog.md
  book/src/livenessprobe.md
  book/src/node-driver-registrar.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#235 Add new ChubaoFS driver to driver.md
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#238 add more detail about deprecations and breaking changes in 1.17
  book/src/kubernetes-changelog.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#231 drivers: add kadalu driver to list
  book/src/drivers.md
Labels: approved, cncf-cla: no, cncf-cla: yes, lgtm, release-note-none, size/XS

#240 Add Dell EMC CSI drivers for Unity, PowerMax, Isilon & VxFlexOS
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#225 Update Openebs CSI driver feature support
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#241 Update volume expansion status for 1.14 through 1.16
  book/src/volume-expansion.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#245 Update cinder csi driver info
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#244 Add IBM Spectrum Scale CSI Driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#229 Add new Zadara-CSI driver to driver.md
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#249 pod info on mount: fix some errors
  book/src/csi-driver-object.md
  book/src/pod-info.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#248 update sandstone csi driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#250 modify the error url about storage-crds
  book/src/csi-driver-object.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, sig/docs, size/XS

#252 chubaofs not support raw block
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
