Repository kubernetes-csi/docs, pull requests merged in 2019-09, with the labels that each got.

#206 Add OpenEBS to list of CSI drivers
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#203 Update features for ROBIN CSI
  book/src/drivers.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#210 Update cloning to Beta
  book/src/kubernetes-changelog.md
  book/src/volume-cloning.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#209 ephemeral volumes in Kubernetes 1.16
  book/src/csi-driver-object.md
  book/src/ephemeral-local-volumes.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#211 Replace Azure CSI Driver links to official drivers
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
