Repository kubernetes-csi/docs, pull requests merged in 2019-10, with the labels that each got.

#213 Update qingcloud csi
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#215 Update for AWS EBS/EFS/FSx CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#217 Consolidation of driver feature columns
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#212 Update CSI sidecar versions
  book/src/external-attacher.md
  book/src/external-provisioner.md
  book/src/external-resizer.md
  book/src/external-snapshotter.md
  book/src/node-driver-registrar.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#219 Update 1.16 versions and remove unsupported 1.13 versions
  book/src/SUMMARY.md
  book/src/external-attacher.md
  book/src/external-provisioner.md
  book/src/external-resizer.md
  book/src/external-snapshotter.md
  book/src/livenessprobe.md
  book/src/node-driver-registrar.md
  book/src/volume-cloning.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#218 Add Intel PMEM-CSI to drivers
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
