Repository kubernetes-csi/docs, pull requests merged in 2020-11, with the labels that each got.

#380 Add Sangfor Block Storage(EDS) CSI Driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#384 update CSI drivers for qingcloud-csi and qingstor-csi
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#383 add doc for TokenRequests and RequiresRepublish fields
  book/src/SUMMARY.md
  book/src/csi-driver-object.md
  book/src/token-requests.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#378 Add doc for snapshot validation webhook
  book/src/SUMMARY.md
  book/src/snapshot-restore-feature.md
  book/src/snapshot-validation-webhook.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#386 Update CSI driver features for Hedvig
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#387 Update brokenLink for e2e test
  book/src/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#385 Move CSIVolumeFSGroupPolicy to beta
  book/src/csi-driver-object.md
  book/src/support-fsgroup.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#382 List Container Storage Interface (CSI) Driver for Veritas InfoScale volumes
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#389 Update Pure CSI driver to support Ephemeral storage
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#390 Add Vultr CSI Driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
