Repository kubernetes-csi/docs, pull requests merged in 2020-04, with the labels that each got.

#287 Add CSI driver for Tencent CBS, CFS and COSFS to list
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#293 Add xing-yang to owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#292 Add Raw Block and Topology support for Pure CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#289 Add Hetzner Cloud CSI Driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#294 ibm block v1.1 add raw block and DS8K
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#295 Add Bigtera VirtualStor CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#290 Update docs for 1.18
  book/src/csi-objects.md
  book/src/external-attacher.md
  book/src/external-provisioner.md
  book/src/external-resizer.md
  book/src/external-snapshotter.md
  book/src/kubernetes-changelog.md
  book/src/livenessprobe.md
  book/src/node-driver-registrar.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#286 Update link for IBM Spectrum Scale CSI Driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#297 Update doc for csi-gcs driver to indicate support for dynamic provisioning
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#299 add manila-csi driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#298 add hyperv-csi-driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#300 Update ceph-csi rbd feature support
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#296 add Infinidat CSI driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#301 Update Pure Storage capabilites and spec version support
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#302 Update snapshot-controller to v2.1.0
  book/src/snapshot-controller.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#303 Add Huawei CSI Support
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#304 Add Commvault Hedvig CSI Driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#306 Mark Cloning as GA
  book/src/volume-cloning.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#307 Fix feature name to match standard
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#309 Update Huawei CSI Support
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#311 Update GCE PD CSI Driver feature list
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#313 Update GCE PD Feature List for Raw Block
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#312 Add link to new CSI announce mailing list
  book/src/developing.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
