Repository kubernetes-csi/docs, pull requests merged in 2020-01, with the labels that each got.

#257 Add Sangfor Distributed File Storage(EDS) CSI driver to driver.md
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#259 Update provisioner and CSINode versions for 1.17
  book/src/csi-node-object.md
  book/src/external-provisioner.md
  book/src/topology.md
  book/src/volume-limits.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#256 docs: remove old generated html files
  book/src/_book/Archive.html
  book/src/_book/CSI-Driver.html
  book/src/_book/CSI-Kubernetes.html
  book/src/_book/Deployment.html
  book/src/_book/Development.html
  book/src/_book/Drivers.html
  book/src/_book/Example.html
  book/src/_book/Home.html
  book/src/_book/Kubernetes-1.9.html
  book/src/_book/References.html
  book/src/_book/Setup.html
  book/src/_book/Testing-Clients.html
  book/src/_book/Testing-Drivers.html
  book/src/_book/Testing.html
  book/src/_book/Troubleshooting.html
  book/src/_book/Usage.html
  book/src/_book/index.html
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#258 Update external-attacher sidecar version
  book/src/external-attacher.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#261 Add livenessprobe release
  book/src/livenessprobe.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#264 drivers.md: update drivers with ephemeral support
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#268 Updated NexentaStor driver feature support
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#267 Extend DigitalOcean CSI driver features by raw block and expansion
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#251 modify the error url about setup-csi-snapshotter
  book/src/external-snapshotter.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, sig/docs, size/XS
