Repository kubernetes-csi/docs, pull requests merged in 2020-05, with the labels that each got.

#308 fix typos
  book/src/functional-testing.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#317 Update doc for csi-gcs driver to indicate support for Volume Expansion
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#320 Remove the timeout issue note from the snapshot-restore doc.
  book/src/snapshot-restore-feature.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#321 Update NexentaStor version and supported features
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#322 Fix status version table
  book/src/node-driver-registrar.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#323 Add Dell EMC CSI drivers for PowerStore
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#319 add secrets-store-csi-driver in drivers
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#325 Fix broken livenessprobe version table
  book/src/livenessprobe.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
