Repository kubernetes-csi/docs, pull requests merged in 2020-12, with the labels that each got.

#379 Add doc for volume health monitor
  book/src/SUMMARY.md
  book/src/external-health-monitor-agent.md
  book/src/external-health-monitor-controller.md
  book/src/volume-health-monitor.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#392 fix csi spec compatibility support for vsphere driver
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#393 fix wrong feature gate name
  book/src/token-requests.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#394 Include CSIDriver FSGroupPolicy in SUMMARY
  book/src/SUMMARY.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#396 Add k8s 1.20 changelog and update patch versions
  book/src/external-attacher.md
  book/src/external-provisioner.md
  book/src/external-resizer.md
  book/src/external-snapshotter.md
  book/src/kubernetes-changelog.md
  book/src/snapshot-controller.md
  book/src/snapshot-validation-webhook.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#399 Update drivers.md
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#398 storage capacity tracking
  book/src/SUMMARY.md
  book/src/storage-capacity-tracking.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#397 CSI Extension for Ephemeral Volume Support, generic ephemeral
  book/src/ephemeral-local-volumes.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#395 IBM block v1.4
  book/src/drivers.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS
