Repository kubernetes-csi/docs, pull requests merged in 2022-04, with the labels that each got.

#506 Add CRD API Documentation
  README.md
  book/src/SUMMARY.md
  book/src/api.md
  book/src/api/volume-snapshot.md
  hack/gen-api.json
  hack/gen-api.sh
Labels: cncf-cla: yes, lgtm, approved, size/XXL, release-note-none

#513 add smb csi driver and update nfs driver
  book/src/drivers.md
Labels: cncf-cla: yes, lgtm, approved, release-note-none, size/XS

#512 add Azure Blob CSI driver
  book/src/drivers.md
Labels: cncf-cla: yes, lgtm, approved, release-note-none, size/XS

#508 Update security considerations for CSI inline ephemeral volumes
  book/src/ephemeral-local-volumes.md
Labels: cncf-cla: yes, lgtm, approved, release-note, size/S
